run:
  skip-dirs:
    - vendor
    - bin
    - var
    - tmp
  skip-files:
    - \.pb\.go$

govet:
  enable:
    - fieldalignment

linters:
  disable-all: false
  enable:
    - dogsled
    - errcheck
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - whitespace
    - gosimple
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - unparam
    - usestdlibvars
    - wastedassign
    - zerologlint
    - gochecknoglobals
    - gochecknoinits
    - godox
    - nakedret
    - cyclop
    - lll
  disable:
    - gci #the sort of imports
    - nlreturn #empty space before return
    - gofumpt #add more go fmt, but need to be implemetned inside the all IDE
    - tagalign #usefull align, but not implemented inside the all IDE yet
    - wsl #force to use emptylines
    - depguard # import management
    - govet

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
        xml: camel
  godot:
    scope: all
    period: false
    capital: false
  cyclop:
    max-complexity: 13