version: '3.8'

services:
  api:
    restart: always
    build: ./
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=qwerty123

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./dbschema/000001_init.up.sql:/docker-entrypoint-initdb.d/dbschema/000001_init.up.sql
    environment:
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - "5433:5432"
